version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  meli:
    build: .
    environment: 
      - ADDR=0.0.0.0:8080
      - REDIS_URL=redis://redis
      - TRACE_ADDR=""
    ports: 
      - "8080:8080"